export const CLEAR_TIMETABLE_DATA = 'CLEAR_TIMETABLE_DATA';

export const GET_TIMETABLE_DATA_REQUEST = 'GET_TIMETABLE_DATA_REQUEST';
export const GET_TIMETABLE_DATA_SUCCESS = 'GET_TIMETABLE_DATA_SUCCESS';
export const GET_TIMETABLE_DATA_FAILURE = 'GET_TIMETABLE_DATA_FAILURE';

export const SEARCH_TIMETABLE_DATA_REQUEST = 'SEARCH_TIMETABLE_DATA_REQUEST';
export const SEARCH_TIMETABLE_DATA_SUCCESS = 'SEARCH_TIMETABLE_DATA_SUCCESS';
export const SEARCH_TIMETABLE_DATA_FAILURE = 'SEARCH_TIMETABLE_DATA_FAILURE';
