export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';

export const AUTH_REGISTER = 'AUTH_REGISTER';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_FAILURE = 'AUTH_REGISTER_FAILURE';

export const AUTH_GET_STATUS = 'AUTH_GET_STATUS';
export const AUTH_GET_STATUS_SUCCESS = 'AUTH_GET_STATUS_SUCCESS';
export const AUTH_GET_STATUS_FAILURE = 'AUTH_GET_STATUS_FAILURE';

export const AUTH_SAVECHANGE = 'AUTH_SAVECHANGE';
export const AUTH_SAVECHANGE_SUCCESS = 'AUTH_SAVECHANGE_SUCCESS';
export const AUTH_SAVECHANGE_FAILURE = 'AUTH_SAVECHANGE_FAILURE';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const MEMO_POST = 'MEMO_POST';
export const MEMO_POST_SUCCESS = 'MEMO_POST_SUCCESS';
export const MEMO_POST_FAILURE = 'MEMO_POST_FAILURE';

export const MEMO_LIST = 'MEMO_LIST';
export const MEMO_LIST_SUCCESS = 'MEMO_LIST_SUCCESS';
export const MEMO_LIST_FAILURE = 'MEMO_LIST_FAILURE';

export const MEMO_EDIT = 'MEMO_EDIT';
export const MEMO_EDIT_SUCCESS = 'MEMO_EDIT_SUCCESS';
export const MEMO_EDIT_FAILURE = 'MEMO_EDIT_FAILURE';

export const MEMO_REMOVE = 'MEMO_REMOVE';
export const MEMO_REMOVE_SUCCESS = 'MEMO_REMOVE_SUCCESS';
export const MEMO_REMOVE_FAILURE = 'MEMO_REMOVE_FAILURE';

export const MEMO_STAR = 'MEMO_STAR';
export const MEMO_STAR_SUCCESS = 'MEMO_STAR_SUCCESS';
export const MEMO_STAR_FAILURE = 'MEMO_STAR_FAILURE';

export const REPLY_POST = 'REPLY_POST';
export const REPLY_POST_SUCCESS = 'REPLY_POST_SUCCESS';
export const REPLY_POST_FAILURE = 'REPLY_POST_FAILURE';

export const REPLY_REMOVE = 'REPLY_REMOVE';
export const REPLY_REMOVE_SUCCESS = 'REPLY_REMOVE_SUCCESS';
export const REPLY_REMOVE_FAILURE = 'REPLY_REMOVE_FAILURE';

export const MESSAGE_SEND = 'MESSAGE_SEND';
export const MESSAGE_SEND_SUCCESS = 'MESSAGE_SEND_SUCCESS';
export const MESSAGE_SEND_FAILURE = 'MESSAGE_SEND_FAILURE';

export const MESSAGE_LIST = 'MESSAGE_LIST';
export const MESSAGE_LIST_SUCCESS = 'MESSAGE_LIST_SUCCESS';
export const MESSAGE_LIST_FAILURE = 'MESSAGE_LIST_FAILURE';

export const MESSAGE_REMOVE = 'MESSAGE_REMOVE';
export const MESSAGE_REMOVE_SUCCESS = 'MESSAGE_REMOVE_SUCCESS';
export const MESSAGE_REMOVE_FAILURE = 'MESSAGE_REMOVE_FAILURE';
