export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const AUTH_REGISTER = 'AUTH_REGISTER';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_FAILURE = 'AUTH_REGISTER_FAILURE';

export const AUTH_GET_STATUS = 'AUTH_GET_STATUS';
export const AUTH_GET_STATUS_SUCCESS = 'AUTH_GET_STATUS_SUCCESS';
export const AUTH_GET_STATUS_FAILURE = 'AUTH_GET_STATUS_FAILURE';

export const AUTH_SEARCH = 'AUTH_SEARCH';
export const AUTH_SEARCH_SUCCESS = 'AUTH_SEARCH_SUCCESS';
export const AUTH_SEARCH_FAILURE = 'AUTH_SEARCH_FAILURE';

export const CHAT_SEND_MESSAGE = 'CHAT_SEND_MESSAGE';
export const CHAT_SEND_MESSAGE_SUCCESS = 'CHAT_SEND_MESSAGE_SUCCESS';
export const CHAT_SEND_MESSAGE_FAILURE = 'CHAT_SEND_MESSAGE_FAILURE';

export const CHAT_GET_MESSAGE = 'CHAT_GET_MESSAGE';
export const CHAT_GET_MESSAGE_SUCCESS = 'CHAT_GET_MESSAGE_SUCCESS';
export const CHAT_GET_MESSAGE_FAILURE = 'CHAT_GET_MESSAGE_FAILURE';

export const CHAT_GET_CHATLIST = 'CHAT_GET_CHATLIST';
export const CHAT_GET_CHATLIST_SUCCESS = 'CHAT_GET_CHATLIST_SUCCESS';
export const CHAT_GET_CHATLIST_FAILURE = 'CHAT_GET_CHATLIST_FAILURE';
