export const GET_WEATHERDATA_REQUEST = 'GET_WEATHERDATA_REQUEST';
export const GET_WEATHERDATA_SUCCESS = 'GET_WEATHERDATA_SUCCESS';
export const GET_WEATHERDATA_FAILURE = 'GET_WEATHERDATA_FAILURE';

export const GET_FORECASTDATA_REQUEST = 'GET_FORECASTDATA_REQUEST';
export const GET_FORECASTDATA_SUCCESS = 'GET_FORECASTDATA_SUCCESS';
export const GET_FORECASTDATA_FAILURE = 'GET_FORECASTDATA_FAILURE';

export const GET_CITYLISTDATA_REQUEST = 'GET_CITYLISTDATA_REQUEST';
export const GET_CITYLISTDATA_SUCCESS = 'GET_CITYLISTDATA_SUCCESS';
export const GET_CITYLISTDATA_FAILURE = 'GET_CITYLISTDATA_FAILURE';
