// user action types below
export const ACCOUNT_ADDNEWUSER_REQUEST = 'ACCOUNT_ADDNEWUSER_REQUEST';
export const ACCOUNT_ADDNEWUSER_SUCCESS = 'ACCOUNT_ADDNEWUSER_SUCCESS';
export const ACCOUNT_ADDNEWUSER_FAILURE = 'ACCOUNT_ADDNEWUSER_FAILURE';

export const ACCOUNT_LOGIN_REQUEST = 'ACCOUNT_LOGIN_REQUEST';
export const ACCOUNT_LOGIN_SUCCESS = 'ACCOUNT_LOGIN_SUCCESS';
export const ACCOUNT_LOGIN_FAILURE = 'ACCOUNT_LOGIN_FAILURE';

export const ACCOUNT_CHECKTOKEN_REQUEST = 'ACCOUNT_CHECKTOKEN_REQUEST';
export const ACCOUNT_CHECKTOKEN_SUCCESS = 'ACCOUNT_CHECKTOKEN_SUCCESS';
export const ACCOUNT_CHECKTOKEN_FAILURE = 'ACCOUNT_CHECKTOKEN_FAILURE';

// marker action types below
export const MARKER_ADDNEWMARKER_REQUEST = 'MARKER_ADDNEWMARKER_REQUEST';
export const MARKER_ADDNEWMARKER_SUCCESS = 'MARKER_ADDNEWMARKER_SUCCESS';
export const MARKER_ADDNEWMARKER_FAILURE = 'MARKER_ADDNEWMARKER_FAILURE';

export const MARKER_GETALLMARKERS_REQUEST = 'MARKER_GETALLMARKERS_REQUEST';
export const MARKER_GETALLMARKERS_SUCCESS = 'MARKER_GETALLMARKERS_SUCCESS';
export const MARKER_GETALLMARKERS_FAILURE = 'MARKER_GETALLMARKERS_FAILURE';

export const MARKER_UPDATEMARKER_REQUEST = 'MARKER_UPDATEMARKER_REQUEST';
export const MARKER_UPDATEMARKER_SUCCESS = 'MARKER_UPDATEMARKER_SUCCESS';
export const MARKER_UPDATEMARKER_FAILURE = 'MARKER_UPDATEMARKER_FAILURE';

export const MARKER_DELETEMARKER_REQUEST = 'MARKER_DELETEMARKER_REQUEST';
export const MARKER_DELETEMARKER_SUCCESS = 'MARKER_DELETEMARKER_SUCCESS';
export const MARKER_DELETEMARKER_FAILURE = 'MARKER_DELETEMARKER_SUCCESS';

export const MARKER_GETMARKERS_BYKEYWORD_REQUEST = 'MARKER_GETMARKERS_BYKEYWORD_REQUEST';
export const MARKER_GETMARKERS_BYKEYWORD_SUCCESS = 'MARKER_GETMARKERS_BYKEYWORD_SUCCESS';
export const MARKER_GETMARKERS_BYKEYWORD_FAILURE = 'MARKER_GETMARKERS_BYKEYWORD_FAILURE';