export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';

export const AUTH_REGISTER_REQUEST = 'AUTH_REGISTER_REQUEST';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_FAILURE = 'AUTH_REGISTER_FAILURE';

export const AUTH_GETSTATUS_REQUEST = 'AUTH_GETSTATUS_REQUEST';
export const AUTH_GETSTATUS_SUCCESS = 'AUTH_GETSTATUS_SUCCESS';
export const AUTH_GETSTATUS_FAILURE = 'AUTH_GETSTATUS_FAILURE';

export const AUTH_LOGOUT_REQUEST = 'AUTH_LOGOUT_REQUEST';

export const GET_POSTINGDATA_REQUEST = 'GET_POSTINGDATA_REQUEST';
export const GET_POSTINGDATA_SUCCESS = 'GET_POSTINGDATA_SUCCESS';
export const GET_POSTINGDATA_FAILURE = 'GET_POSTINGDATA_FAILURE';

export const HELP_POSTINGVOC_REQUEST = 'HELP_POSTINGVOC_REQUEST';
export const HELP_POSTINGVOC_SUCCESS = 'HELP_POSTINGVOC_SUCCESS';
export const HELP_POSTINGVOC_FAILURE = 'HELP_POSTINGVOC_FAILURE';
