export const ACCOUNT_LOGIN_REQUEST = 'ACCOUNT_LOGIN_REQUEST';
export const ACCOUNT_LOGIN_SUCCESS = 'ACCOUNT_LOGIN_SUCCESS';
export const ACCOUNT_LOGIN_FAILURE = 'ACCOUNT_LOGIN_FAILURE';

export const ACCOUNT_GET_INFO_REQUEST = 'ACCOUNT_GET_INFO_REQUEST';
export const ACCOUNT_GET_INFO_SUCCESS = 'ACCOUNT_GET_INFO_SUCCESS';
export const ACCOUNT_GET_INFO_FAILURE = 'ACCOUNT_GET_INFO_FAILURE';

export const ACCOUNT_SIGNUP_REQUEST = 'ACCOUNT_SIGNUP_REQUEST';
export const ACCOUNT_SIGNUP_SUCCESS = 'ACCOUNT_SIGNUP_SUCCESS';
export const ACCOUNT_SIGNUP_FAILURE = 'ACCOUNT_SIGNUP_FAILURE';

export const ACCOUNT_SIGNUP_CONFIRM_REQUEST = 'ACCOUNT_SIGNUP_CONFIRM_REQUEST';
export const ACCOUNT_SIGNUP_CONFIRM_SUCCESS = 'ACCOUNT_SIGNUP_CONFIRM_SUCCESS';
export const ACCOUNT_SIGNUP_CONFIRM_FAILURE = 'ACCOUNT_SIGNUP_CONFIRM_FAILURE';

export const ACCOUNT_LOGOUT_REQUEST = 'ACCOUNT_LOGOUT_REQUEST';

export const ACCOUNT_MANAGE_BOOKMARKS_REQUEST = 'ACCOUNT_MANAGE_BOOKMARKS_REQUEST';
export const ACCOUNT_MANAGE_BOOKMARKS_SUCCESS = 'ACCOUNT_MANAGE_BOOKMARKS_SUCCESS';
export const ACCOUNT_MANAGE_BOOKMARKS_FAILURE = 'ACCOUNT_MANAGE_BOOKMARKS_FAILURE';

export const ACCOUNT_HASBOOKMARKED_REQUEST = 'ACCOUNT_HASBOOKMARKED_REQUEST';
export const ACCOUNT_HASBOOKMARKED_SUCCESS = 'ACCOUNT_HASBOOKMARKED_SUCCESS';
export const ACCOUNT_HASBOOKMARKED_FAILURE = 'ACCOUNT_HASBOOKMARKED_FAILURE';

export const ACCOUNT_GET_BOOKMARKS_REQUEST = 'ACCOUNT_GET_BOOKMARKS_REQUEST';
export const ACCOUNT_GET_BOOKMARKS_SUCCESS = 'ACCOUNT_GET_BOOKMARKS_SUCCESS';
export const ACCOUNT_GET_BOOKMARKS_FAILURE = 'ACCOUNT_GET_BOOKMARKS_FAILURE';

export const POSTING_POST_NEW_REQUEST = 'POSTING_POST_NEW_REQUEST';
export const POSTING_POST_NEW_SUCCESS = 'POSTING_POST_NEW_SUCCESS';
export const POSTING_POST_NEW_FAILURE = 'POSTING_POST_NEW_FAILURE';

export const POSTING_SAVE_TEMP_REQUEST = 'POSTING_SAVE_TEMP_REQUEST';
export const POSTING_SAVE_TEMP_SUCCESS = 'POSTING_SAVE_TEMP_SUCCESS';
export const POSTING_SAVE_TEMP_FAILURE = 'POSTING_SAVE_TEMP_FAILURE';

export const POSTING_LOAD_ALL_REQUEST = 'POSTING_LOAD_ALL_REQUEST';
export const POSTING_LOAD_ALL_SUCCESS = 'POSTING_LOAD_ALL_SUCCESS';
export const POSTING_LOAD_ALL_FAILURE = 'POSTING_LOAD_ALL_FAILURE';

export const POSTING_LOAD_BY_CATEGORY_REQUEST = 'POSTING_LOAD_BY_CATEGORY_REQUEST';
export const POSTING_LOAD_BY_CATEGORY_SUCCESS = 'POSTING_LOAD_BY_CATEGORY_SUCCESS';
export const POSTING_LOAD_BY_CATEGORY_FAILURE = 'POSTING_LOAD_BY_CATEGORY_FAILURE';

export const POSTING_LOAD_TEMP_LIST_REQUEST = 'POSTING_LOAD_TEMP_LIST_REQUEST';
export const POSTING_LOAD_TEMP_LIST_SUCCESS = 'POSTING_LOAD_TEMP_LIST_SUCCESS';
export const POSTING_LOAD_TEMP_LIST_FAILURE = 'POSTING_LOAD_TEMP_LIST_FAILURE';

export const POSTING_LOAD_TEMP_ITEM_REQUEST = 'POSTING_LOAD_TEMP_ITEM_REQUEST';
export const POSTING_LOAD_TEMP_ITEM_SUCCESS = 'POSTING_LOAD_TEMP_ITEM_SUCCESS';
export const POSTING_LOAD_TEMP_ITEM_FAILURE = 'POSTING_LOAD_TEMP_ITEM_FAILURE';

export const POSTING_READ_ITEM_REQUEST = 'POSTING_READ_ITEM_REQUEST';
export const POSTING_READ_ITEM_SUCCESS = 'POSTING_READ_ITEM_SUCCESS';
export const POSTING_READ_ITEM_FAILURE = 'POSTING_READ_ITEM_FAILURE';